### ISSUE TITLE
Writing equations in the response

### ISSUE THREAD

**Issue by aakhmetz** [pjbouchet/respondR#1]
Thank you for a nice package! I wonder how would you write equations in the Word file, so they would properly knit after? I've tried to do, but I get an error from my Rstudio every time

**Comment by pjbouchet** [comment]
Thank you for your interest in the package! Have you tried writing your equation using LaTeX formatted math rather than using the Word equation editor?

**Comment by aakhmetz** [comment]
I finally moved back to my jupyter :o
